
name: Build Dev Images

env:
  REGISTRY: ghcr.io
  WEBADE_JCRS_URL: ${{ secrets.WEBADE_JCRS_URL }}
  NPMRC: ${{ secrets.NPMRC }}
on:
  workflow_dispatch:

jobs:
  call-mvn-client:
    uses: ./.github/workflows/mvn-client.yml
    secrets: inherit
  call-mvn-server:
    uses: ./.github/workflows/mvn-server.yml
    with:
      EMAIL_ENABLED: true
      SMTP_HOSTNAME: sample_user
      SMTP_USER: sample_user@sample.com
      SMTP_PASSWORD: ${{ secrets.DEV_SMTP_PASSWORD}}
      SMTP_FROM_EMAIL: noreply@sample.com
      ADMIN_EMAIL: admin_user@sample.com
      EMAIL_SYNC_ERROR_FREQUENCY: 30
      EMAIL_SYNC_SEND_FREQUENCY: 60
      EMAIL_SYNC_ERROR_SUBJECT: ERROR
      EMAIL_SYNC_SUBJECT: MESSAGE
      DEFAULT_APPLICATION_ENVIRONMENT: wfnews
    secrets: inherit
