name: Main Merge

on:
  push:
    branches: [ "main" ]

jobs:
  # https://github.com/marketplace/actions/aqua-security-trivy
  trivy-repo:
    name: Trivy-Repo
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.3.0
        with:
          scan-type: "fs"
          ignore-unfixed: true
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results.sarif"
  
  terragrunt-plan:
    name: Terragrunt Plan
    runs-on: ubuntu-18.04
    steps:
      - name: Run terraform plan for generic Dev environment  
        uses: ./.github/workflows/terragrunt-plan.yml
