# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          servers: >
            [
              {
                "id":"central",
                "username": "chrprest@gov.bc.ca", 
                "password": "turning_WIDENING*gyre"
              },
              {
                "id":"snapshots",
                "username": "chrprest@gov.bc.ca", 
                "password": "turning_WIDENING*gyre"
              }
            ]
          repositories: >
            [
              {
                "id": "snapshots",
                "name": "libs-snapshots",
                "url":"https://bwa.nrs.gov.bc.ca/int/artifactory/libs-snapshot"
              },
              {
                "id": "central", 
                "name": "libs-release",
                "url":"https://bwa.nrs.gov.bc.ca/int/artifactory/libs-release"
              }
            ]
      - name: Build with Maven
        run: mvn --settings settings.xml --batch-mode --update-snapshots -f server/pom.xml package
