name: Deploy using terragrunt

on:
  # workflow_call:
  workflow_dispatch:

# inputs:
#   CLIENT_IMAGE:
#     type: string
#     required: true
#   SERVER_IMAGE:
#     type: string
#     required: true
#   TARGET_ENV:
#     type: string
#     required: true


env:
  TF_VERSION: 1.2.2
  TG_VERSION: 0.37.1
  TG_SRC_PATH: terraform
  TFC_WORKSPACE: wfnews-dev

jobs:
  plan:
    name: Plan
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          aws-region: ca-central-1

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TFC_TEAM_TOKEN }}

      - uses: peter-murray/terragrunt-github-action@v1.0.0
        with:
          terragrunt_version: ${{ env.TG_VERSION }}
      
      - name: Terragrunt Apply
        # working-directory: ${{env.TG_SRC_PATH}}/${{ input.TARGET_ENV }}
        working-directory: ${{env.TG_SRC_PATH}}/dev
        env:
          # CLIENT_IMAGE: ${{ input.CLIENT_IMAGE }}
          # SERVER_IMAGE: ${{ input.SERVER_IMAGE }}
          CLIENT_IMAGE: ghcr.io/vivid-cpreston/nr-bcws-wfnews-client:main
          SERVER_IMAGE: ghcr.io/vivid-cpreston/nr-bcws-wfnews-server:main
          DB_PASS: ${{ secrets.DB_PASS }}
        run: terragrunt plan

